name: Test

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: 'Ubuntu 22.10'
            host_os_docker_image: ubuntu:22.10
          - name: 'Ubuntu 22.04'
            host_os_docker_image: ubuntu:22.04
          - name: 'Debian 11'
            host_os_docker_image: debian:bullseye
    steps:
      - name: Check out the source code
        uses: actions/checkout@v2

      - name: Test the provisioning
        run: |
          ./bin/test ${{ matrix.host_os_docker_image }}
        shell: bash
